version: '3.8'

services:
  postgres-dumps:
    image: postgres:16.4
    container_name: dumps-postgres
    environment:
      POSTGRES_USER: dumps
      POSTGRES_PASSWORD: dumps-pass
      POSTGRES_DB: dumps
    ports:
      - "5432:5432"
    volumes:
      - dumps_postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dumps
    command: sh -c "echo 'Listing files in /app:' && ls -al /app && echo 'Current working directory:' && pwd && dotnet Web.dll"
    ports:
      - "5001:5001"
    depends_on:
      - postgres-dumps
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=dumps;Username=dumps;Password=dumps_pass

volumes:
  dumps_postgres_data:
