version: '3.8'

services:
  dumps-api:
    build:
      context: .
      dockerfile: ./src/Presentation/Dumps.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=dumps_db;Username=postgres;Password=dumps_pass
    depends_on:
      - postgres
      - migrations
      - seq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dumps_pass
      POSTGRES_DB: dumps_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    container_name: service-migrations
    build:
      context: .
      dockerfile: ./src/Presentation/Dumps.Api/Dockerfile
      target: migrations
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=dumps_db;Username=postgres;Password=dumps_pass
    depends_on:
      - postgres
  
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"  # Expose the Seq UI on port 5341
    environment:
      - ACCEPT_EULA=Y  # Accept the Seq EULA

volumes:
  postgres_data:
